# Generated by Django 2.1.5 on 2019-04-03 08:26

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0008_auto_20190331_0651'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_details',
            name='date_of_birth',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
